# Generated by Django 5.1.6 on 2025-03-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportverifier',
            name='user',
        ),
        migrations.DeleteModel(
            name='PassportOfficer',
        ),
        migrations.DeleteModel(
            name='PassportVerifier',
        ),
    ]
