# Generated by Django 5.1.6 on 2025-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('UserNaMe', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('PassWoRd', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verifier_id', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
