# Generated by Django 5.1.2 on 2025-03-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassportRegistration',
        ),
    ]
