# Generated by Django 5.1.2 on 2025-03-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_passportapplication_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
