# Generated by Django 5.1.2 on 2025-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('govt_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='employee_photos/')),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('alternative_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('reporting_officer', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=20)),
                ('user_role', models.CharField(max_length=50)),
                ('jurisdiction', models.TextField()),
                ('access_level', models.CharField(max_length=20)),
                ('verify_authority', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('digital_signature', models.ImageField(upload_to='digital_signatures/')),
            ],
        ),
    ]
